### ISSUE TITLE
q: how do I choose the language?

### ISSUE THREAD

**Issue by clarity99** [simonw/ospeak#16]
how do I set the language for the voice?

**Comment by simonw** [comment]
According to https://platform.openai.com/docs/guides/text-to-speech/supported-languages it should work for a bunch of languages without you needing to configure anything:

> Afrikaans, Arabic, Armenian, Azerbaijani, Belarusian, Bosnian, Bulgarian, Catalan, Chinese, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, Galician, German, Greek, Hebrew, Hindi, Hungarian, Icelandic, Indonesian, Italian, Japanese, Kannada, Kazakh, Korean, Latvian, Lithuanian, Macedonian, Malay, Marathi, Maori, Nepali, Norwegian, Persian, Polish, Portuguese, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Swahili, Swedish, Tagalog, Tamil, Thai, Turkish, Ukrainian, Urdu, Vietnamese, and Welsh.
